name: Delete clean Gitpod workspaces weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * MON' # At 9 AM UTC, weekly only on Monday

jobs:
  delete-clean-workspaces:
    name: Clean Gitpod workspaces weekly
    runs-on: ubuntu-latest
    steps:
      - name: Delete clean Gitpod workspaces
        uses: Siddhant-K-code/delete-clean-workspaces@v1.1
        with:
          GITPOD_TOKEN: ${{ secrets.GITPOD_PAT_TOKEN }}
          PRINT_SUMMARY: false
